<?php
//module/Almacen/view/almacen/almacen/add.phtml

$title  = 'Add new almacen';
$this->headtitle($title);
?>
<h1><?php echo $this->escapehtml($title);?></h1>
<?php 
    $form   =   $this->form;
    $form->setAttribute('action',$this->url('almacen',array('action'    =>  'add')));
    $form->prepare();
    $formLabel = $this->plugin('formLabel');
    echo $this->form()->openTag($form);
    echo $this->formhidden($form->get('idalmacen'));
?>
<div class="form_element">
<?php
    echo $this->formrow($form->get('nombre'));
?>
</div>
<div class="form_element">
<?php
    echo $this->formrow($form->get('direccion'));
?>
</div>
<div class="form_element">
<?php
    echo $this->formrow($form->get('cp'));
?>
</div>
<div class="form_element">
<?php
    echo $this->formrow($form->get('idciudad'));
?>
</div>
<div class="form_element">
<?php
    echo $this->formrow($form->get('idestado'));
?>
</div>
<div class="form_element">
<?php
    echo $this->formrow($form->get('idpais'));
?>
</div>
<div class="form_element">
<?php
    echo $this->formsubmit($form->get('submit'));
    echo $this->form()->closeTag();
?>
</div>