<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'EntradaSalida\Module'                        => __DIR__ . '/Module.php',
    'EntradaSalida\Controller\EntradaSalidaController' => __DIR__ . '/src/EntradaSalida/Controller/EntradaSalidaController.php',
    'EntradaSalidaTest\Framework\TestCase'        => __DIR__ . '/tests/EntradaSalida/Framework/TestCase.php',
    'EntradaSalidaTest\SampleTest'                => __DIR__ . '/tests/EntradaSalida/SampleTest.php',
);
