<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Estadisticas\Module'                        => __DIR__ . '/Module.php',
    'Estadisticas\Controller\EstadisticasController' => __DIR__ . '/src/Estadisticas/Controller/EstadisticasController.php',
    'EstadisticasTest\Framework\TestCase'        => __DIR__ . '/tests/Estadisticas/Framework/TestCase.php',
    'EstadisticasTest\SampleTest'                => __DIR__ . '/tests/Estadisticas/SampleTest.php',
);
