<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Producto\Module'                        => __DIR__ . '/Module.php',
    'Producto\Controller\ProductoController' => __DIR__ . '/src/Producto/Controller/ProductoController.php',
    'ProductoTest\Framework\TestCase'        => __DIR__ . '/tests/Producto/Framework/TestCase.php',
    'ProductoTest\SampleTest'                => __DIR__ . '/tests/Producto/SampleTest.php',
);
