<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Champion\Module'                        => __DIR__ . '/Module.php',
    'Champion\Controller\ChampionController' => __DIR__ . '/src/Champion/Controller/ChampionController.php',
    'Producto\Controller\ProductoController' => __DIR__ . '/src/Producto/Controller/ProductoController.php',
    'ChampionTest\Framework\TestCase'        => __DIR__ . '/tests/Champion/Framework/TestCase.php',
    'ChampionTest\SampleTest'                => __DIR__ . '/tests/Champion/SampleTest.php',
);
